parameters:
    btn_event.provider.event_node_content.class: Btn\EventBundle\Provider\EventNodeContentProvider

services:
    btn_event.provider.event_node_content:
        class: %btn_event.provider.event_node_content.class%
        arguments:
            provider: @btn_event.provider.event
