services:

    btn.event:
        class: Btn\EventBundle\Service\EventManager
        arguments:
            params: %btn_event%
            em: @doctrine.orm.entity_manager

    btn.event.content_provider:
        class: Btn\EventBundle\Service\EventContentProvider
        arguments:
            router: '@router'
            em:     '@doctrine.orm.entity_manager'

    btn.event.calendar:
        class:      Btn\EventBundle\Calendar\Calendar
        arguments:
            router: '@router'
            twig:   '@twig'
            parameters: %btn_event%
