parameters:
    btn_event.form.event_control.class: Btn\EventBundle\Form\EventControlForm
    btn_event.form.type.event.class: Btn\EventBundle\Form\Type\EventCategoryType

services:
    btn_event.form.event_control:
        parent: btn_admin.form.abstract
        class: %btn_event.form.event_control.class%
        calls:
            - [setClass, ['%btn_event.event.class%']]
        tags:
            - { name: form.type, alias: btn_event_form_event_control }

    btn_event.form.type.event:
        class: %btn_event.form.type.event.class%
        calls:
            - [setClass, ['%btn_event.event.class%']]
        tags:
            - { name: form.type, alias: btn_event }
