services:
    #add link to the CP top menu
    btn_event.menu_navbar.media_item:
        class: %btn_admin.menu_item.class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "btn_event.eventcontrol_index", "btn_event_eventcontrol_index", [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_admin.menu_navbar.modules }
