# services:
services:
    btn_event.calendar:
        class:      Btn\EventBundle\Calendar\Calendar
        arguments:
            router: '@router'
            twig: '@twig'
            parameters: %btn_event.calendar%

    btn_event.provider.event:
        class: %btn_base.provider.entity.class%
        parent: btn_base.provider.abstract_entity
        arguments: ['%btn_event.event.class%']
